[package]
name = "unpluggy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "1.2.0"
tokio = {version = "1.37.0", features = ["full"]}
websocket = "0.27.1"
serde_json = "1.0"